- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- link:
    ~/.vimrc:
    ~/.gitconfig:
    ~/.yaourtrc:
    ~/.config/fish/config.fish: fish.conf
    ~/.Xresources:

