- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- link:
    ~/.vimrc:
    ~/.gitconfig:
    ~/.yaourtrc:
    ~/.config/fish/config.fish: fish.conf
    ~/.config/redshift.conf:
    ~/.config/dunst/dunstrc:
    ~/.Xresources:
    ~/.ssh/authorized_keys:
    ~/.config/beets/config.yaml: beets.yaml
    ~/.config/fontconfig/fonts.conf: fontconfig.xml

