position: top
height: 25
modules-left: 
    - sway/workspaces
    - sway/mode
    - sway/window
modules-right:
    - idle_inhibitor
    - pulseaudio
    - network
    - battery
    - clock
    - tray
sway/window:
    format: '  {}'
idle_inhibitor:
    format: '{icon}'
    format-icons:
        activated: ''
        deactivated: ''
pulseaudio:
    format: "{icon} {volume}%"
    format-muted: " {volume}%"
    format-bluetooth: "{icon} {volume}% "
    on-click: pavucontrol
    format-icons:
        headphones: ""
        default: ["", ""]
network:
    format-wifi: " {essid} ({signalStrength}%)"
    on-click: nm-connection-editor
battery:
    format: "{icon} {capacity}%"
    format-charging: " {capacity}%"
    format-plugged: " {capacity}%"
    format-alt: "{icon} {time}"
    format-icons: ["", "", "", "", ""]
clock:
    interval: 1
    format: ' <span font_family="monospace">{:%H:%M:%S}</span>'
